services:
  - type: web
    name: real-estate-django
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn real_estate_rental.wsgi:application"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: real_estate_rental.settings
      - key: SECRET_KEY
        value: abc
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        value: .onrender.com
      - key: DB_NAME
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        sync: false
      - key: EMAIL_HOST_USER
        sync: false
      - key: EMAIL_HOST_PASSWORD
        sync: false
