# Generated by Django 4.2.20 on 2025-05-15 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Введите номер телефона в формате +77171234567', max_length=20, null=True),
        ),
    ]
