name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  format:
    name: Format & Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install formatting tools
        run: |
          python -m pip install --upgrade pip
          pip install autoflake isort black flake8

      - name: Ensure format.sh is executable
        run: git update-index --chmod=+x scripts/format.sh

      - name: Run formatting script
        run: scripts/format.sh

  test:
    name: Run Django tests
    runs-on: ubuntu-latest
    needs: format
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install -r requirements.txt
          # if you still need pytest:
          pip install pytest

      - name: Run Django built-in tests
        run: python manage.py test --verbosity=2