name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  # Переназначаем параметры БД из CI
  DB_ENGINE: django.db.backends.postgresql
  DB_NAME: test_real_estate_db
  DB_USER: postgres
  DB_PASSWORD: postgres
  DB_HOST: 127.0.0.1
  DB_PORT: 5432

jobs:
  format:
    name: Format & Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with: { python-version: '3.x' }
      - name: Install formatting tools
        run: |
          python -m pip install --upgrade pip
          pip install autoflake isort black flake8
      - name: Run formatting script
        run: scripts/format.sh

  test:
    name: Run Django tests
    runs-on: ubuntu-latest
    needs: format

    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test_real_estate_db
        ports:
          - 5432:5432
        # ждём, пока Postgres не станет готов
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with: { python-version: '3.x' }

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: Run Django built-in tests
        env:
          # прокидываем в Django settings
          DB_ENGINE: ${{ env.DB_ENGINE }}
          DB_NAME:   ${{ env.DB_NAME }}
          DB_USER:   ${{ env.DB_USER }}
          DB_PASSWORD: ${{ env.DB_PASSWORD }}
          DB_HOST:   ${{ env.DB_HOST }}
          DB_PORT:   ${{ env.DB_PORT }}
        run: python manage.py test --verbosity=2
